version: "3.9"

services:
  fastapi:
    image: image-fastapi
    build: .
    container_name: innovation-platform-api
    ports:
      - "8000:8000"
    volumes:
        - ./:/innovation-platform
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=building-software-mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=ipt_idiomas
      - SECRET_KEY=c5bfff0866d57527a06b026508053986
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
  database:
    image: mysql:latest
    container_name: innovation-platform-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: innovation-platform
    volumes:
      - ./mysql:/var/lib/mysql
