version: "3.9"

services:
  innp.fastapi:
    image: image-fastapi
    build: .
    container_name: INNP.API
    ports:
      - "8000:8000"
    volumes:
        - ./:/innovation-platform
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=innp.database
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=innovation_platform
      - SECRET_KEY=c5bfff0866d57527a06b026508053986
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - WEB_ORIGIN=http://localhost:5187
  innp.database:
    image: mysql:latest
    container_name: INNP.Database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: innovation_platform
    volumes:
      - ./mysql:/var/lib/mysql
